spring:
  application:
    name: performance_reservation
  profiles:
    group:
      dev: dev
      test: test
    default: dev
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/reservation;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    defer-datasource-initialization: true
  sql:
    init:
      mode: always



---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
