name: dev cd pipeline

on:
  push:
    branches:
      - 'feat-*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: action/checkout@3

      - name: JDK install
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Authority setting
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew build

      - name: Print test coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.5
        with:
        title: 📝 Jacoco Test Coverage
        paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        update-comment: true

